# Generated by Django 3.0.4 on 2021-05-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='provincial',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='API.Provincials'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wards',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='API.Districts'),
            preserve_default=False,
        ),
    ]
